AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Cluster for Hosting Microservices

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: MicroservicesCluster

Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
